
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/petergtz/pegomock"
  version = "v2.1.0"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  name = "github.com/briandowns/spinner"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/elazarl/go-bindata-assetfs"

[[constraint]]
  branch = "master"
  name = "github.com/google/go-github"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-multierror"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-version"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/colorstring"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  branch = "master"
  name = "github.com/lkysow/go-gitlab"

[[constraint]]
  branch = "master"
  name = "github.com/benmatselby/go-azuredevops/azuredevops"

[[constraint]]
  name = "github.com/go-test/deep"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/flynn-archive/go-shlex"

[[constraint]]
  branch = "master"
  name = "github.com/docker/docker"
