name: ci-link-checker-image

on:
  push:
    # paths:
    #   - '.github/website_link_checker/**'
    # branches:
    #   - "master"
  workflow_dispatch:

defaults:
  run:
    working-directory: .github/website_link_checker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Packages Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: echo "TODAY=$(date +"%m%d%Y")" >> $GITHUB_ENV
    - name: build ci-link-checker:${{env.TODAY}} image
      run: |
        docker build -t ghcr.io/runatlantis/ci-link-checker:${{env.TODAY}} .
    - name: publish ci-link-checker:${{env.TODAY}} image
      run: |
        docker push ghcr.io/runatlantis/ci-link-checker:${{env.TODAY}}
        docker tag ghcr.io/runatlantis/ci-link-checker:${{env.TODAY}} ghcr.io/runatlantis/ci-link-checker:latest
        docker push ghcr.io/runatlantis/ci-link-checker:latest
